/* config.h.  Generated by configure.  */
/* Define if the C compiler supports BOOL */
/* #undef HAVE_BOOL */

#define VERSION "1.1.1"

#define PACKAGE "gtapecalc"

#define PIXMAP_DIR "/usr/local/share/gtapecalc/pixmaps/"

#define HELP_DIR "/usr/local/share/gtapecalc/doc/help/"

/* #undef GNOME_HELP_BROWSER */

/* #undef NETSCAPE */

/* #undef LYNX */

#define NO_BROWSER

/* #undef GSVIEWER */

#define NO_GV

/* Define if you need the GNU extensions to compile */
/* #undef _GNU_SOURCE */

/* Name of package */
#define PACKAGE "gtapecalc"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Version number of package */
#define VERSION "1.1.1"
